# Generated by Django 4.2.3 on 2023-07-26 11:15

import apps.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=apps.products.models.name_file),
        ),
        migrations.CreateModel(
            name='ProductDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='products.product')),
            ],
        ),
    ]
