# Generated by Django 4.2.3 on 2023-07-27 10:35

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productdescriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=apps.products.models.name_file),
        ),
    ]
