# Generated by Django 4.2.3 on 2023-08-08 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_sharedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shared_with_users',
            field=models.ManyToManyField(related_name='shared_by_others', through='products.SharedProducts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedproducts',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedproducts',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
