version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_api
    expose:
      - 8000
    env_file:
      - ./config/settings/.env.dev
    depends_on:
      - db
    volumes:
      - .:/code
      - /code/venv

  db:
    image: postgres:12-alpine
    container_name: postgres_api
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    env_file:
      - ./config/settings/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    container_name: nginx_api
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:


