version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    expose:
      - 8000
    env_file:
      - ./config/settings/.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    env_file:
      - ./config/settings/.env.dev

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

