version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_api
    ports:
      - 5001:5001
    depends_on:
      - db
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - config/settings/.env.dev

  db:
    image: postgres:12-alpine
    container_name: postgres_api
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    env_file:
      - config/settings/.env.dev

  worker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: django_celery_worker
    command: celery -A config worker -l info
    depends_on:
      - web
      - db
      - rabbitmq
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - config/settings/.env.dev

volumes:
  static_volume:
  media_volume:


