version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind "0.0.0.0:5001" --access-logfile - --error-logfile - config.wsgi:application
    container_name: django_api
    ports:
      - 5001:5001
    depends_on:
      - db
      - rabbitmq
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - config/settings/.env.dev

  web_ws:
    build:
      context: .
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 5002 config.asgi:application
    container_name: django_api_ws
    ports:
      - 5002:5002
    depends_on:
      - db
      - rabbitmq
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - config/settings/.env.dev

  db:
    image: postgres:12-alpine
    container_name: postgres_api
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  nginx:
    build: ./nginx
    container_name: nginx_api
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - 80:30396
    depends_on:
      - web
      - web_ws

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_api
    ports:
      - 1025:1025
      - 8025:8025

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    env_file:
      - config/settings/.env.dev

  worker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: django_celery_worker
    command: celery -A config worker -l info
    depends_on:
      - web_ws
      - web
      - db
      - rabbitmq
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - config/settings/.env.dev

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"


volumes:
  # postgres_data:
  static_volume:
  media_volume:


