version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind "0.0.0.0:5001" --access-logfile - --error-logfile - config.wsgi:application
    container_name: django_api
    ports:
      - 5001:5001
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - config/settings/.env.prod

  web_ws:
    build:
      context: .
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 5002 config.asgi:application
    container_name: django_api_ws
    ports:
      - 5002:5002
    depends_on:
      - db
      - rabbitmq
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - config/settings/.env.dev

  web_fast_api:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.fastapi
    command: uvicorn urls:app --reload --proxy-headers --port 5003
    container_name: fastapi
    ports:
      - 5003:5003

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    env_file:
      - config/settings/.env.prod

  worker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: django_celery_worker
    command: celery -A config worker -l info -c 2 --max-memory-per-child=150000 --max-tasks-per-child=4
    depends_on:
      - web_ws
      - web
      - rabbitmq
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - config/settings/.env.prod

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  static_volume:
  media_volume:


