version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_api
    ports:
      - 5001:5001
    depends_on:
      - db
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - config/settings/.env.dev

  db:
    image: postgres:12-alpine
    container_name: postgres_api
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_api
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  static_volume:
  media_volume:


