# Generated by Django 4.2.3 on 2023-07-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(limit_choices_to={'productimage__count__lt': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
    ]
